SET FOREIGN_KEY_CHECKS = 0;
drop table seminario.cliente;
drop table seminario.permiso;
drop table seminario.permiso_rol;
drop table seminario.persona;
drop table seminario.rol;
drop table seminario.usuario;
drop table seminario.usuario_rol;
drop table seminario.localidad;
drop table seminario.localidad_clasificacion;
drop table seminario.viaje;
drop table seminario.vehiculo;
drop table seminario.calificacion;
drop table seminario.comision_cobrada;
drop table seminario.pasajero_viaje;
drop table seminario.localidad_viaje;
drop table seminario.maneja;
SET FOREIGN_KEY_CHECKS = 1; 
