CREATE TABLE PERSONA (
	ID_PERSONA INTEGER AUTO_INCREMENT,
	NOMBRES VARCHAR(60) NOT NULL,
	APELLIDOS VARCHAR(60) NOT NULL,
	TIPO_DOC SMALLINT NOT NULL,
	NRO_DOC BIGINT NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	DOMICILIO VARCHAR(120) NOT NULL,
	TELEFONO VARCHAR(16) NOT NULL,
	DESCRIPCION TEXT,
	ESTADO BOOLEAN NOT NULL,

	PRIMARY KEY (ID_PERSONA)
);

CREATE TABLE USUARIO (
	ID_USUARIO INTEGER NOT NULL AUTO_INCREMENT,
	ID_PERSONA INTEGER,
	NOMBRE_USUARIO VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	DESCRIPCION TEXT,
	ESTADO BOOLEAN NOT NULL,

	PRIMARY KEY (ID_USUARIO),
	FOREIGN KEY (ID_PERSONA) REFERENCES PERSONA (ID_PERSONA)
);

CREATE TABLE ROL (
	ID_ROL INTEGER NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL,
	NOMBRE_AMIGABLE VARCHAR(30) NOT NULL,
	DESCRIPCION TEXT,
	ESTADO BOOLEAN NOT NULL,

	PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO_ROL (
	ID_USUARIO INTEGER NOT NULL,
	ID_ROL INTEGER NOT NULL,

	PRIMARY KEY (ID_USUARIO, ID_ROL),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
	FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

// LAS TABLAS DE ACA ABAJO FUERON MODIFICADAS

CREATE TABLE PERMISO (
	ID_PERMISO INTEGER,
	RECURSO VARCHAR(200),
	LECTURA BOOLEAN,
	ESCRITURA BOOLEAN,

	PRIMARY KEY (ID_PERMISO)
);

CREATE TABLE PERMISO_ROL (
	ID_PERMISO INTEGER NOT NULL,
	ID_ROL INTEGER NOT NULL,
	FECHA_MODIFICACION DATE,

	PRIMARY KEY(ID_PERMISO,ID_ROL),
	FOREIGN KEY (ID_PERMISO) REFERENCES PERMISO(ID_PERMISO),
	FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)

);