CREATE TABLE PERSONA (
	NOMBRES VARCHAR(60) NOT NULL,
	APELLIDOS VARCHAR(60) NOT NULL,
	TIPO_DOC SMALLINT NOT NULL,
	NRO_DOC BIGINT NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	DOMICILIO VARCHAR(120) NOT NULL,
	TELEFONO VARCHAR(16) NOT NULL,
	DESCRIPCION TEXT,
	ESTADO BOOLEAN NOT NULL,

	PRIMARY KEY (TIPO_DOC, NRO_DOC)
);

CREATE TABLE USUARIO (
	ID_USUARIO INTEGER NOT NULL,
	PERSONA_TIPO_DOC SMALLINT,
	PERSONA_NRO_DOC BIGINT,
	NOMBRE_USUARIO VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(40) NOT NULL,
	DESCRIPCION TEXT,
	ESTADO BOOLEAN NOT NULL,

	PRIMARY KEY (ID_USUARIO),
	FOREIGN KEY (PERSONA_TIPO_DOC, PERSONA_NRO_DOC) REFERENCES PERSONA (TIPO_DOC, NRO_DOC)
);

CREATE TABLE ROL (
	ID_ROL INTEGER NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	NOMBRE_AMIGABLE VARCHAR(30) NOT NULL,
	DESCRIPCION TEXT,
	ESTADO BOOLEAN NOT NULL,

	PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO_ROL (
	ID_USUARIO INTEGER NOT NULL,
	ID_ROL INTEGER NOT NULL,

	PRIMARY KEY (ID_USUARIO, ID_ROL),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
	FOREIGN KEY (ID_ROL) REFERENCES ROL (ID_ROL)
);

CREATE TABLE PERMISO (
	ID_ROL INTEGER,
	RECURSO VARCHAR(200),
	LECTURA BOOLEAN,
	ESCRITURA BOOLEAN
);

